### PR TITLE
1 0 x

### PR DESCRIPTION
**Pull request by JDutil**
Based on https://github.com/joshmcarthur/spree-import-products/pull/11 but updated to reference Spree 1.0.x instead of 0.80.x.

This is much cleaner to merge than https://github.com/joshmcarthur/spree-import-products/pull/14/files

### CODE REVIEW

**Comment by joshmcarthur** [comment]
Hey @jdutil,

I'll try and find some time tonight to sit down and merge in this pull request, and the others referencing other versions of Spree. I'm keen to get master as little used as possible by instead referencing the correct branches in the Versionfile, so may merge this into a new 1.0.x branch (similar to on your fork).

Cheers!

**Comment by sbounmy** [comment]
just saw this PR, maybe we get something with https://github.com/joshmcarthur/spree-import-products/pull/16 @jdutil @joshmcarthur

**Comment by joshmcarthur** [comment]
Hey @sbounmy,

I'll take a look at #16 tonight as well - I'll probably go for some mixture of the two (#16 seems to have some weird merges from other repos?), but I like having testing support in there.

Sound good?

**Comment by sbounmy** [comment]
hey @joshmcarthur 

Thanks for taking time to review pull requests!

I've been quickly trough #16 and it really provided a spree 1.0.x support with some partial namespacing and so.
Tested with integration tests here #17 and manually is working pretty well so far.

I am open to other ways to make this gem spree 1.0.x compatible :)

**Comment by JDutil** [comment]
Closing since this was merged into a branch.  IMO though it would be good to update master to be up to date with the 1-1-x branch to make contributions to keep up with spree edge simpler.  Then create stable branches when master would no longer be compatible.

**Pull request closed without merging**
